// js/synthetic-people.js
// Runtime helpers for your 722-member pool
// Uses window.MembersPool generated by members-pool.js

(function () {
  if (!window.MembersPool) {
    console.warn("MembersPool not loaded yet. SyntheticPeople will not work until it is.");
  }

  const SyntheticPeople = {

    // --- BASIC GETTERS ---
    getAll() {
      return window.MembersPool?.slice() || [];
    },

    getById(id) {
      return window.MembersPool?.find(m => m.id === id) || null;
    },

    getRandom(count = 1, excludeIds = []) {
      const pool = this.getAll().filter(m => !excludeIds.includes(m.id));
      if (pool.length === 0) return count === 1 ? null : [];
      if (count === 1) return pool[Math.floor(Math.random() * pool.length)];
      const shuffled = pool.sort(() => 0.5 - Math.random());
      return shuffled.slice(0, count);
    },

    getOnlineMembers() {
      return this.getAll().filter(m => m.online);
    },

    getTypingMembers() {
      return this.getAll().filter(m => m.typing);
    },

    getVerifiedMembers() {
      return this.getAll().filter(m => m.verified);
    },

    // --- STATUS / AVATAR HELPERS ---
    setOnline(id, status = true) {
      const member = this.getById(id);
      if (member) member.online = status;
    },

    setTyping(id, typing = true) {
      const member = this.getById(id);
      if (member) member.typing = typing;
    },

    setAvatar(id, avatarUrl) {
      const member = this.getById(id);
      if (member) member.avatar = avatarUrl;
    },

    // --- ROLE HELPERS ---
    getByRole(role) {
      return this.getAll().filter(m => m.role === role);
    },

    getAdmins() {
      return this.getByRole('admin');
    },

    getMods() {
      return this.getByRole('mod');
    },

    getMembers() {
      return this.getByRole('member');
    },

    randomAdmin() {
      const admins = this.getAdmins();
      return admins[Math.floor(Math.random() * admins.length)] || null;
    },

    randomMod() {
      const mods = this.getMods();
      return mods[Math.floor(Math.random() * mods.length)] || null;
    },

    randomMember() {
      const members = this.getMembers();
      return members[Math.floor(Math.random() * members.length)] || null;
    },

    // --- ADDITIONAL UTILITY ---
    countByRole(role) {
      return this.getByRole(role).length;
    },

    getCounts() {
      const all = this.getAll();
      return {
        total: all.length,
        online: all.filter(m => m.online).length,
        verified: all.filter(m => m.verified).length,
        typing: all.filter(m => m.typing).length,
        admins: this.getAdmins().length,
        mods: this.getMods().length,
        members: this.getMembers().length
      };
    }

  };

  // Expose globally
  window.SyntheticPeople = SyntheticPeople;

})();
